done
mohammed-almossa/prep-0222-code-solutions pull request #6
Opened 2022-02-24 07:53 UTC by mohammed-almossa

![image](https://user-images.githubusercontent.com/70071146/155481503-d3f7d34e-dd7e-4a9f-bc72-6e7df1083f1a.png)

2022-02-24 07:54 UTC, mohammed-almossa commented
im not sure if this was write i feel like there was something missing on this one

2022-02-24 16:01 UTC, thebearingedge requested changes

2022-02-24 16:01 UTC, thebearingedge commented on prep-css-box-model/style.css
> +  border: darkgray 3px double;
Hi Mohammed, to get the double border working, you want to put the color last.

https://developer.mozilla.org/en-US/docs/Web/CSS/border#syntax

2022-02-25 04:56 UTC, mohammed-almossa commented on prep-css-box-model/style.css
> +  border: darkgray 3px double;
![image](https://user-images.githubusercontent.com/70071146/155656233-f7082be0-d997-49fd-9ca3-ae2cb1b1385d.png)

2022-02-25 05:08 UTC, thebearingedge approved these changes

2022-02-26 14:08 UTC, merged