done
mohammed-almossa/prep-0222-code-solutions pull request #7
Opened 2022-02-24 08:26 UTC by mohammed-almossa

![image](https://user-images.githubusercontent.com/70071146/155486738-c6dbe40b-35ca-4178-870e-5740994bff23.png)

2022-02-24 16:04 UTC, thebearingedge requested changes

2022-02-24 16:04 UTC, thebearingedge commented on prep-css-display/index.html
> +  </ul>
Hi Mohammed, we want to put the visible content in the `<body></body>` element of the document instead of the `<head></head>`.

2022-02-25 05:02 UTC, mohammed-almossa commented
![image](https://user-images.githubusercontent.com/70071146/155656822-ae7eda06-116c-419b-9ce3-576258ab8447.png)

2022-02-25 05:17 UTC, thebearingedge approved these changes

2022-02-26 14:08 UTC, merged